name: Update Json File
on:
    workflow_dispatch:
jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Enter a server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_SECRET }}
                script: |
                    ls -a

                