name: Update Json File
on:
    workflow_dispatch:
jobs:
    Deploy:
        name: Update JSON File
        runs-on: ubuntu-latest
        steps:
            - name: Remote SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_SECRET }}
                script: |
                    cd tiuinws-chatbot/
                    tmux kill-session -t chat-1
                    python3 update_json.py
                    tmux new -s chat-1
                    python3 main.py