name: Update Json File
on:
    workflow_dispatch:
jobs:
    Deploy:
        name: Update Chatbot Datasets
        runs-on: ubuntu-latest
        steps:
            - name: Remote SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_SECRET }}
                script: |
                    ls -a
                    cd tiuinws-chatbot/
                    ls -a
                    tmux ls